language: python
sudo: false
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pip install -r requirements-travis.txt"
script:
  - flaskbb translations compile
  - tox
after_success:
  - coverage combine tests
  - coveralls
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
